# ---
# Djazz Compose file
# Please refer to the: docs/compose.md for more information
# ---
name: djazz
services:

  djazz:
    image: ghcr.io/azataiot/djazz:latest
    env_file:
      - .env
    environment:
      - DEBUG=1
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
    profiles:
      - test
      - production

  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-djazz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - debug
      - production

  mail:
    image: axllent/mailpit
    restart: always
    expose:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    profiles:
      - debug


volumes:
  pg-data:


