# ---
# Djazz Compose file
# Please refer to the: docs/compose.md for more information
# ---
name: djazz
services:

  djazz:
    image: ghcr.io/azataiot/djazz:latest
    environment:
      - DEBUG=0
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
    profiles:
      - production

  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-djazz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - debug
      - production

  redis:
    image: redis:7.2-alpine
    restart: always
    expose:
      - 6379
    profiles:
      - debug



volumes:
  pg-data:


