# ---
# Djazz Compose file
# Please refer to the: docs/compose.md for more information
# ---
name: djazz
services:

  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-djazz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - debug
      - production

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    profiles:
      - debug

  mail:
    image: axllent/mailpit
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    profiles:
      - debug


volumes:
  pg-data:


