# Generated by Django 5.0.6 on 2024-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_category_seo_description_category_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=68),
        ),
    ]
