# Generated by Django 5.0.6 on 2024-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_post_seo_keywords_alter_post_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
